import requests
import json
import time

# --- OMNIVAULT LIVE DEPLOYMENT CONFIG ---
# This points to your live Vercel API
BASE_URL = "https://omnivault-core.vercel.app/api/get-weights"

def integrate_vault_intelligence(weight_id):
    print(f"\n[SCANNER] Connecting to Cloud Vault: omnivault-core.vercel.app")
    print(f"[SCANNER] Fetching ID: {weight_id}...")
    
    try:
        # Fetching from the LIVE Vercel endpoint
        response = requests.get(f"{BASE_URL}?id={weight_id}")
        
        if response.status_code == 404:
            print("[ERROR] Weight ID not found in the cloud index.")
            return None
            
        response.raise_for_status()
        data = response.json()
        
        print("\n[SUCCESS] Intelligence Package Received from Vercel.")
        print(f"Source Document: {data.get('origin_document', 'Unknown')}")
        print(f"Model Integrity: Verified by OmniVault API")
        
        weights = data.get('weights', [])
        print(f"\n[RAW DATA] Extracted {len(weights)} Optimized Weights:")
        
        # Displaying the "Massive Numbers" for the panel
        print(f"START: {weights[:5]}")
        print("...")
        print(f"END:   {weights[-5:]}")
        
        return weights

    except Exception as e:
        print(f"\n[ERROR] Connection failed. Ensure Laptop 2 has internet access.")
        print(f"Technical Detail: {e}")
        return None

if __name__ == "__main__":
    print("====================================================")
    print("   OMNIVAULT: MULTI-LAPTOP LIVE CLOUD DEMO          ")
    print("====================================================")
    
    # In the demo, Laptop 2 enters the ID generated by Laptop 1 on Vercel
    target_id = input("Enter the Secure Weight ID from Vercel: ").strip()
    
    if target_id:
        result = integrate_vault_intelligence(target_id)
        
        if result:
            print("\n----------------------------------------------------")
            print("   VERIFICATION: PHYSICAL-DIGITAL LINK CONFIRMED")
            print("----------------------------------------------------")
            print(f"The local machine on Laptop 2 has integrated ")
            print(f"intelligence from the Seller on Laptop 1.")
            print("====================================================\n")